--CREATE USER CONO IDENTIFIED BY CONO;
--GRANT RESOURCE, CONNECT TO CONO;


DROP TABLE MEMBER;
CREATE TABLE MEMBER(
	ID VARCHAR2(10) PRIMARY KEY,
	PW VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(10) NOT NULL,
	PHONE VARCHAR2(15) NOT NULL,
	BIRTH DATE NOT NULL,
	GENDER VARCHAR2(2),
	ADDRESS VARCHAR2(30),
	EMAIL VARCHAR2(20),
	GRADE VARCHAR2(5) DEFAULT 'USER', -- USER, SUPERVISOR, ADMIN, SLEEP , BLACK
	STATUS VARCHAR2(1) DEFAULT 'Y',
	REGDATE DATE DEFAULT SYSDATE,
	MODIFYDATE DATE DEFAULT SYSDATE
);

INSERT INTO MEMBER VALUES(
    'CHLTJDFKR', 'CHLTJDFKR', '최성락', '010-0101-0101', SYSDATE, NULL, NULL, NULL, 'ADMIN', DEFAULT ,SYSDATE, NULL
);
INSERT INTO MEMBER VALUES(
    'CSL931', 'TJDFKR1!', '최성락', '010-0101-0101', SYSDATE, 'M', '서울시', 'CSL931@GMAIL.COM', 'ADMIN', DEFAULT ,SYSDATE, SYSDATE
);
SELECT * FROM MEMBER WHERE STATUS = 'Y';

commit;