-- CREATE USER CONO IDENTIFIED BY CONO;
-- GRANT RESOURSE, CONNECT TO CONO;


DROP TABLE MEMBER;
CREATE TABLE MEMBER(
	ID VARCHAR2(10) PRIMARY KEY,
	PW VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(10) NOT NULL,
	PHONE VARCHAR2(15) NOT NULL,
	BIRTH DATE NOT NULL,
	GENDER VARCHAR2(2),
	ADDRESS VARCHAR2(30),
	EMAIL VARCHAR2(20),
	GRADE VARCHAR2(5) DEFAULT '사용자',
	STATUS VARCHAR2(1) DEFAULT 'Y',
	REGDATE DATE DEFAULT SYSDATE,
	MODIFYDATE DATE DEFAULT SYSDATE
);