--CREATE USER CONO IDENTIFIED BY CONO;
--GRANT RESOURCE, CONNECT TO CONO;


DROP TABLE MEMBER;
CREATE TABLE MEMBER(
	ID VARCHAR2(10) PRIMARY KEY,
	PW VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(10) NOT NULL,
	PHONE VARCHAR2(15) NOT NULL,
	BIRTH DATE NOT NULL,
	GENDER VARCHAR2(3) NOT NULL,
	ADDRESS VARCHAR2(30) DEFAULT '-',
	EMAIL VARCHAR2(20) DEFAULT '-',
	GRADE VARCHAR2(9) DEFAULT '일반', -- 일반, 사장님, 관리자, 휴면 , 블랙
	STATUS VARCHAR2(1) DEFAULT 'Y',
	REGDATE DATE DEFAULT SYSDATE,
	MODIFYDATE DATE DEFAULT SYSDATE,
    POINT NUMBER DEFAULT 0
);

INSERT INTO MEMBER VALUES('CHLTJDFKR', 'CHLTJDFKR', '최성락', '010-0101-0101', SYSDATE, '남', '서울시', 'CSL931@GMAIL.COM', '관리자', DEFAULT ,SYSDATE, DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES('QWE', '11', '최성락', '010-0101-0101', SYSDATE, '남', '서울시', 'CSL931@GMAIL.COM', DEFAULT, DEFAULT ,SYSDATE, DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES('ASD', '11', '최성락', '010-0101-0101', SYSDATE, '남', '서울시', 'CSL931@GMAIL.COM', DEFAULT, DEFAULT ,SYSDATE, DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES('ZXC', '11', '최성락', '010-0101-0101', SYSDATE, '남', '서울시', 'CSL931@GMAIL.COM', DEFAULT, DEFAULT ,SYSDATE, DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES('WER', '11', '최성락', '010-0101-0101', SYSDATE, '남', '서울시', 'CSL931@GMAIL.COM', DEFAULT, DEFAULT ,SYSDATE, DEFAULT, DEFAULT);
INSERT INTO MEMBER VALUES('SDF', '11', '최성락', '010-0101-0101', SYSDATE, '남', '서울시', 'CSL931@GMAIL.COM', DEFAULT, DEFAULT ,SYSDATE, DEFAULT, DEFAULT);

SELECT * FROM MEMBER;

-- 업데이트 쿼리
UPDATE MEMBER SET NAME = '' WHERE ID = '';

SELECT ID, NAME, PHONE, BIRTH, GENDER, ADDRESS, EMAIL, GRADE, STATUS, REGDATE, MODIFYDATE, POINT
FROM MEMBER WHERE STATUS = 'Y';

-- 뷰 생성 시 활용
CREATE OR REPLACE VIEW SUPERVISOR_MEMBER
AS
SELECT ID, NAME, PHONE, BIRTH, GENDER, ADDRESS, EMAIL, GRADE, STATUS, REGDATE, MODIFYDATE, POINT
FROM MEMBER WHERE STATUS = 'Y';

commit;